
trigger:
  branches:
    exclude:
    - '*'

pr:
  branches:
    exclude:
    - '*'
  
variables:
  solution: '**/MeadowCLI.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool:
  vmImage: windows-2019

stages:
- stage: Build_Release
  jobs:
    - job: Create_Release
      steps:
        - task: NuGetToolInstaller@1
        - task: NuGetCommand@2
          inputs:
            feedsToUse: 'select' 
            restoreSolution: '$(solution)'
        - task: VSBuild@1
          inputs:
            solution: '$(solution)'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: 'MeadowCLI\bin\Release\net472'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)\Meadow.CLI.$(tagName).zip'
        - task: GitHubRelease@1
          inputs:
            gitHubConnection: 'github.com_lamebrain'
            repositoryName: '$(Build.Repository.Name)'
            action: 'create'
            target: '$(Build.SourceVersion)'
            tagSource: 'userSpecifiedTag'
            tag: '$(tagName)'
            title: '$(title)'
            assets: '$(Build.ArtifactStagingDirectory)\Meadow.CLI.$(tagName).zip'
            isPreRelease: true
            addChangeLog: false