name: Develop Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout Meadow.Logging
      uses: actions/checkout@v4
      with:
        repository: WildernessLabs/Meadow.Logging
        path: Meadow.Logging
        ref: develop
        
    - name: Checkout Meadow.Units
      uses: actions/checkout@v4
      with:
        repository: WildernessLabs/Meadow.Units
        path: Meadow.Units
        ref: develop

    - name: Checkout Meadow.Contracts
      uses: actions/checkout@v4
      with:
        repository: WildernessLabs/Meadow.Contracts
        path: Meadow.Contracts
        ref: develop

    - name: Checkout Meadow.CLI
      uses: actions/checkout@v4
      with:
        path: Meadow.CLI
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          8.0.x
    
    - name: Build CLI
      run: dotnet build -c Release Meadow.CLI/Source/Meadow.CLI.sln

    - name: Unit Test CLI
      run: dotnet test -c Release --no-build --no-restore --filter "FullyQualifiedName~.Unit.Tests" .\Meadow.CLI\Source\Meadow.CLI.sln

      
