name: Develop Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout Meadow.Logging
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Logging
        path: Meadow.Logging
        ref: develop
        
    - name: Checkout Meadow.Units
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Units
        path: Meadow.Units
        ref: develop

    - name: Checkout Meadow.Contracts
      uses: actions/checkout@v3
      with:
        path: Meadow.Contracts
        ref: develop

    - name: Checkout Meadow.CLI
      uses: actions/checkout@v3
      with:
        path: Meadow.CLI
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          8.0.x
    
    - name: Build CLI v1
      run: dotnet build -c Release Meadow.CLI/MeadowCLI.sln

    - name: Build CLI v2
      run: dotnet build -c Release Meadow.CLI/Source/v2/Meadow.CLI.v2.sln

      
